# Generated by Django 5.1.5 on 2025-01-15 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveryapp', '0001_initial'),
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.transaction'),
        ),
    ]
